export const INTERNAL_INVARIANT_CODES = [
  'AUDIT_IMMUTABLE',
  'AUDIT_CHAIN_BROKEN',
  'AUDIT_COUPLING_VIOLATION',
  'HITL_VIOLATION',
  'EXCEPTION_WITHOUT_BASIS',
  'AUDIT_SEQUENCE_CONFLICT',
  'AUDIT_WRITE_INVALID',
  'AUDIT_WRITE_FORBIDDEN_CONTENT',
] as const;

export type InternalInvariantCode = (typeof INTERNAL_INVARIANT_CODES)[number];
